# Generated by Django 5.1.5 on 2026-08-23 04:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flights", "0002_routestats_pricesnapshot"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flight_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha del vuelo"
                    ),
                ),
                (
                    "target_price_pen",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="precio objetivo S/",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("price_below", "Precio por debajo de"),
                            ("deal_detected", "Oferta detectada"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creada en"),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="flights.route",
                        verbose_name="ruta",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="users.telegramuser",
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "alerta",
                "verbose_name_plural": "alertas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_pen",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="precio S/"
                    ),
                ),
                (
                    "message_sent",
                    models.BooleanField(default=False, verbose_name="mensaje enviado"),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="disparada en",
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="alerts.alert",
                        verbose_name="alerta",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="flights.pricesnapshot",
                        verbose_name="snapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "disparo de alerta",
                "verbose_name_plural": "disparos de alerta",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["route", "is_active"], name="idx_alert_route_active"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["user", "is_active"], name="idx_alert_user_active"
            ),
        ),
        migrations.AddIndex(
            model_name="alerttrigger",
            index=models.Index(
                fields=["alert", "triggered_at"], name="idx_trigger_alert_when"
            ),
        ),
    ]
