# Generated by Django 5.1.5 on 2026-08-27 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
        ("flights", "0003_route_use_direct_scrapers"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, verbose_name="correo"
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="email_confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="correo confirmado en"
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="token",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="token"
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="users.telegramuser",
                verbose_name="usuario",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["email", "is_active"], name="idx_alert_email_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="alert",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("email", ""), ("user__isnull", False)),
                    models.Q(
                        ("user__isnull", True), models.Q(("email", ""), _negated=True)
                    ),
                    _connector="OR",
                ),
                name="alert_tiene_un_solo_destinatario",
            ),
        ),
    ]
