# Generated by Django 5.1.5 on 2026-08-23 03:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        db_index=True, unique=True, verbose_name="ID de Telegram"
                    ),
                ),
                (
                    "username",
                    models.CharField(blank=True, max_length=64, verbose_name="usuario"),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=128, verbose_name="nombre"),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[("free", "Gratis"), ("premium", "Premium")],
                        default="free",
                        max_length=10,
                        verbose_name="plan",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="registrado en"
                    ),
                ),
                (
                    "last_active_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="última actividad",
                    ),
                ),
                (
                    "searches_today",
                    models.PositiveIntegerField(
                        default=0, verbose_name="búsquedas de hoy"
                    ),
                ),
                (
                    "searches_reset_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="contador del día",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuario de Telegram",
                "verbose_name_plural": "usuarios de Telegram",
                "ordering": ["-last_active_at"],
            },
        ),
    ]
