# Generated by Django 5.1.5 on 2026-08-28 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="premium_until",
            field=models.DateField(blank=True, null=True, verbose_name="premium hasta"),
        ),
        migrations.CreateModel(
            name="StarPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge_id",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="cargo de Telegram"
                    ),
                ),
                ("stars", models.PositiveIntegerField(verbose_name="estrellas")),
                ("days", models.PositiveIntegerField(verbose_name="días de premium")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="pagado en"),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reembolsado en"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="star_payments",
                        to="users.telegramuser",
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "pago en estrellas",
                "verbose_name_plural": "pagos en estrellas",
                "ordering": ["-created_at"],
            },
        ),
    ]
