# Generated by Django 5.1.5 on 2026-08-20 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "iata_code",
                    models.CharField(
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        verbose_name="código IATA",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nombre")),
                ("city", models.CharField(max_length=100, verbose_name="ciudad")),
                (
                    "region",
                    models.CharField(blank=True, max_length=100, verbose_name="región"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
            ],
            options={
                "verbose_name": "aeropuerto",
                "verbose_name_plural": "aeropuertos",
                "ordering": ["iata_code"],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_monitored",
                    models.BooleanField(default=False, verbose_name="monitoreada"),
                ),
                (
                    "has_direct_flights",
                    models.BooleanField(
                        default=True, verbose_name="tiene vuelo directo"
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Alta"), (2, "Media"), (3, "Baja")],
                        default=3,
                        verbose_name="prioridad",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes_to",
                        to="flights.airport",
                        verbose_name="destino",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes_from",
                        to="flights.airport",
                        verbose_name="origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "ruta",
                "verbose_name_plural": "rutas",
                "ordering": ["priority", "origin_id", "destination_id"],
            },
        ),
        migrations.CreateModel(
            name="FlightOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "airline",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="aerolínea"
                    ),
                ),
                (
                    "flight_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="número de vuelo"
                    ),
                ),
                (
                    "departure_dt",
                    models.DateTimeField(blank=True, null=True, verbose_name="salida"),
                ),
                (
                    "arrival_dt",
                    models.DateTimeField(blank=True, null=True, verbose_name="llegada"),
                ),
                (
                    "stops",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="escalas"
                    ),
                ),
                (
                    "price_pen",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="precio S/"
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="precio original",
                    ),
                ),
                (
                    "original_currency",
                    models.CharField(
                        blank=True, max_length=3, verbose_name="moneda original"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("google_flights", "Google Flights"),
                            ("sky", "Sky Airline"),
                            ("jetsmart", "JetSmart"),
                        ],
                        max_length=20,
                        verbose_name="fuente",
                    ),
                ),
                (
                    "deep_link",
                    models.URLField(blank=True, max_length=1000, verbose_name="enlace"),
                ),
                (
                    "scraped_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="scrapeado en"
                    ),
                ),
                ("search_date", models.DateField(verbose_name="fecha del vuelo")),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="flights.route",
                        verbose_name="ruta",
                    ),
                ),
            ],
            options={
                "verbose_name": "oferta de vuelo",
                "verbose_name_plural": "ofertas de vuelo",
                "ordering": ["price_pen"],
            },
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["is_monitored", "priority"], name="idx_route_monitored_prio"
            ),
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(
                fields=("origin", "destination"), name="uniq_route_origin_destination"
            ),
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.CheckConstraint(
                condition=models.Q(("origin", models.F("destination")), _negated=True),
                name="route_origin_ne_destination",
            ),
        ),
        migrations.AddIndex(
            model_name="flightoffer",
            index=models.Index(
                fields=["route", "search_date", "scraped_at"],
                name="idx_offer_route_date_scrape",
            ),
        ),
        migrations.AddIndex(
            model_name="flightoffer",
            index=models.Index(
                fields=["route", "price_pen"], name="idx_offer_route_price"
            ),
        ),
    ]
