# Generated by Django 5.1.5 on 2026-08-21 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteStats",
            fields=[
                (
                    "route",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="stats",
                        serialize=False,
                        to="flights.route",
                        verbose_name="ruta",
                    ),
                ),
                (
                    "avg_30d",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="promedio 30d S/",
                    ),
                ),
                (
                    "min_30d",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="mínimo 30d S/",
                    ),
                ),
                (
                    "p25_30d",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="percentil 25 30d S/",
                    ),
                ),
                (
                    "median_30d",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="mediana 30d S/",
                    ),
                ),
                (
                    "samples_count",
                    models.PositiveIntegerField(default=0, verbose_name="muestras"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
            ],
            options={
                "verbose_name": "estadística de ruta",
                "verbose_name_plural": "estadísticas de ruta",
                "ordering": ["route_id"],
            },
        ),
        migrations.CreateModel(
            name="PriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_date", models.DateField(verbose_name="fecha del vuelo")),
                (
                    "min_price_pen",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="precio mínimo S/"
                    ),
                ),
                (
                    "avg_price_pen",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="precio promedio S/",
                    ),
                ),
                (
                    "offers_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ofertas encontradas"
                    ),
                ),
                (
                    "cheapest_airline",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="aerolínea más barata"
                    ),
                ),
                (
                    "snapshot_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="tomado en"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="flights.route",
                        verbose_name="ruta",
                    ),
                ),
            ],
            options={
                "verbose_name": "snapshot de precio",
                "verbose_name_plural": "snapshots de precio",
                "ordering": ["-snapshot_at"],
                "indexes": [
                    models.Index(
                        fields=["route", "flight_date", "snapshot_at"],
                        name="idx_snap_route_date_taken",
                    ),
                    models.Index(
                        fields=["route", "min_price_pen"],
                        name="idx_snap_route_minprice",
                    ),
                ],
            },
        ),
    ]
