# Generated by Django 5.1.5 on 2026-08-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_routestats_pricesnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="use_direct_scrapers",
            field=models.BooleanField(
                default=False, verbose_name="usar scrapers directos"
            ),
        ),
    ]
