# Generated by Django 5.1.5 on 2026-08-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0003_route_use_direct_scrapers"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricesnapshot",
            name="days_ahead",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="días de anticipación",
            ),
        ),
    ]
