# Generated by Django 5.1.5 on 2026-09-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0005_backfill_days_ahead"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="alias",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="también buscado como"
            ),
        ),
    ]
