# Generated by Django 5.1.5 on 2026-08-23 04:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.localdate,
                        verbose_name="fecha",
                    ),
                ),
                ("provider", models.CharField(max_length=32, verbose_name="proveedor")),
                (
                    "calls",
                    models.PositiveIntegerField(default=0, verbose_name="llamadas"),
                ),
                (
                    "failures",
                    models.PositiveIntegerField(default=0, verbose_name="fallos"),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(
                        default=0, verbose_name="tokens de entrada"
                    ),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(
                        default=0, verbose_name="tokens de salida"
                    ),
                ),
            ],
            options={
                "verbose_name": "consumo de IA",
                "verbose_name_plural": "consumo de IA",
                "ordering": ["-date", "provider"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "provider"), name="uniq_ai_usage_date_provider"
                    )
                ],
            },
        ),
    ]
